# Generated by Django 3.2 on 2023-02-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App02Lifelog',
            fields=[
                ('global_id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(verbose_name='添加时间')),
                ('tag', models.CharField(default='日常', max_length=128, verbose_name='分类')),
                ('content', models.TextField(verbose_name='内容')),
                ('location_id', models.IntegerField(choices=[(0, '无'), (1, '环卫局宿舍'), (2, '奥莱'), (3, '老家')], db_column='location_Id', default=2, verbose_name='地址')),
            ],
            options={
                'db_table': 'app01_lifelog',
                'managed': False,
            },
        ),
    ]
