# Generated by Django 3.2 on 2022-11-06 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningAppUserinfo',
        ),
    ]
