# Generated by Django 3.2 on 2022-11-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_delete_learningappuserinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningAppUserinfo1',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
