# Generated by Django 3.2 on 2022-11-06 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_learningappuserinfo1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningAppUserinfo1',
        ),
    ]
