# Generated by Django 3.2 on 2022-11-06 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_learningappuserinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LearningAppUserinfo',
            new_name='app01',
        ),
    ]
