# Generated by Django 3.2 on 2022-11-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_rename_app01_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favormusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=128)),
                ('songer', models.CharField(max_length=128)),
                ('addtime', models.DateTimeField()),
                ('album', models.CharField(blank=True, max_length=100, null=True)),
                ('info_from', models.IntegerField()),
                ('duration', models.TimeField()),
                ('global_id', models.PositiveBigIntegerField()),
                ('native_id', models.CharField(max_length=18)),
            ],
            options={
                'db_table': 'favormusic',
                'managed': False,
            },
        ),
    ]
