# Generated by Django 3.2 on 2022-11-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_favormusic'),
    ]

    operations = [
        migrations.CreateModel(
            name='App01Userinfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'app01_userinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LearningAppUserinfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'learning_app_userinfo',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
