# Generated by Django 3.2 on 2023-01-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20221111_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lifelog',
            fields=[
                ('global_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('addtime', models.DateTimeField()),
                ('tag', models.CharField(blank=True, max_length=128, null=True)),
                ('content', models.TextField()),
                ('weather', models.CharField(max_length=64)),
                ('location_id', models.IntegerField(db_column='location_Id')),
            ],
            options={
                'db_table': 'lifelog',
                'db_tablespace': 'second_db',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='App01Userinfo',
        ),
    ]
