# Generated by Django 3.2 on 2023-01-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20230112_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.IntegerField(db_column='location_Id', primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=100)),
                ('attribute', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_id', models.BigIntegerField(unique=True)),
                ('cods', models.CharField(blank=True, db_column='CODS', max_length=32, null=True)),
                ('bar_code', models.BigIntegerField(unique=True)),
                ('product_category', models.CharField(blank=True, max_length=128, null=True)),
                ('production_company', models.CharField(blank=True, max_length=128, null=True)),
                ('product_name', models.CharField(max_length=128)),
                ('unit', models.CharField(blank=True, max_length=32, null=True)),
                ('quantity_unit', models.CharField(blank=True, max_length=32, null=True)),
                ('ingredients', models.CharField(blank=True, max_length=1024, null=True)),
                ('net_weight', models.BigIntegerField(blank=True, null=True)),
                ('shelf_life', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'merchandise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bar_code', models.BigIntegerField()),
                ('alias', models.CharField(blank=True, max_length=32, null=True)),
                ('purchase_channels', models.CharField(max_length=128)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('quantity', models.BigIntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=128, null=True)),
                ('shop_name', models.CharField(blank=True, max_length=128, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('picture', models.IntegerField()),
            ],
            options={
                'db_table': 'purchase',
                'managed': False,
            },
        ),
    ]
