# Generated by Django 3.2 on 2023-01-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_location_merchandise_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Merchandise',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
