# Generated by Django 3.2 on 2023-02-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_auto_20230113_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='App01Lifelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_id', models.PositiveBigIntegerField()),
                ('addtime', models.DateTimeField()),
                ('tag', models.CharField(blank=True, max_length=128, null=True)),
                ('content', models.TextField()),
                ('weather', models.CharField(max_length=64)),
                ('location_id', models.IntegerField(db_column='location_Id')),
            ],
            options={
                'db_table': 'app01_lifelog',
                'managed': False,
            },
        ),
    ]
