# Generated by Django 3.2 on 2023-02-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=32, unique=True, verbose_name='用户名'),
        ),
    ]
