# Generated by Django 3.2 on 2023-03-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_loglife_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loglife',
            name='pub_date',
            field=models.DateTimeField(default='2023-03-05', verbose_name='date published'),
        ),
    ]
