# Generated by Django 3.2 on 2023-03-09 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_title_text_lifelog_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lifelog',
            old_name='title',
            new_name='title_text',
        ),
        migrations.RemoveField(
            model_name='lifelog',
            name='tag_text',
        ),
    ]
