# Generated by Django 3.2 on 2023-03-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20230309_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifelog',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
