# Generated by Django 3.2 on 2023-03-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_lifelog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifelog',
            name='location',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
