# Generated by Django 3.2 on 2023-03-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_lifelog_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifelog',
            name='location',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
