# Generated by Django 3.2 on 2023-03-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20230309_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifelog',
            name='title_text',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
