# Generated by Django 3.2 on 2023-03-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_lifelog_title_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifelog',
            name='title_text',
        ),
        migrations.AddField(
            model_name='lifelog',
            name='tag_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
