# Generated by Django 3.2 on 2023-03-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20230310_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifelog',
            name='tag_id',
        ),
    ]
