# Generated by Django 3.2 on 2023-03-11 00:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_lifelog_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifelog',
            name='content',
            field=models.TextField(null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='lifelog',
            name='location',
            field=models.PositiveSmallIntegerField(choices=[(0, '无'), (1, '环卫局宿舍'), (2, '奥莱'), (3, '老家')], default=2, verbose_name='位置'),
        ),
        migrations.AlterField(
            model_name='lifelog',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='lifelog',
            name='tag',
            field=models.SmallIntegerField(blank=True, help_text='一个tag', null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=200, verbose_name='标签名'),
        ),
    ]
