# Generated by Django 3.2 on 2023-03-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20230311_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifelog',
            name='tags',
            field=models.ManyToManyField(related_name='people', to='blog.Tag'),
        ),
    ]
