# Generated by Django 3.2 on 2023-03-11 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_lifelog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifelog',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=200, unique=True, verbose_name='标签名'),
        ),
    ]
