# Generated by Django 3.2 on 2023-03-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20230311_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifelog',
            name='tag',
        ),
        migrations.AddField(
            model_name='lifelog',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='标签S'),
        ),
    ]
