# Generated by Django 3.2 on 2023-03-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_lifelog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='references_count',
            field=models.IntegerField(default=0, verbose_name='引用次数'),
        ),
    ]
