# Generated by Django 3.2 on 2023-03-27 20:00

import MDEditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=MDEditor.fields.MDTextField(verbose_name='内容'),
        ),
    ]
