# Generated by Django 3.2 on 2023-03-04 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='text',
        ),
    ]
