# Generated by Django 3.2 on 2023-03-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ch', models.CharField(max_length=100, verbose_name='电影名称(中)')),
                ('name_en', models.CharField(max_length=100, verbose_name='电影名称(英)')),
                ('movie_synopsis', models.CharField(max_length=50, verbose_name='电影简介')),
            ],
        ),
    ]
