# Generated by Django 3.2 on 2023-03-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_synopsis',
            field=models.TextField(verbose_name='电影简介'),
        ),
    ]
