# Generated by Django 3.2 on 2023-03-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_movie_movie_synopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name_ch',
            field=models.CharField(max_length=100, unique=True, verbose_name='电影名称(中)'),
        ),
    ]
